# Use official MySQL image
FROM mysql:8.0

# Set environment variables for database initialization
ENV MYSQL_DATABASE=ecommerce_db
ENV MYSQL_USER=root
ENV MYSQL_PASSWORD=gowda
ENV MYSQL_ROOT_PASSWORD=gowda

# Expose MySQL port
EXPOSE 3306

# Default command to run MySQL server
CMD ["mysqld"]
