services:
  - type: pserv
    name: mysql
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile.mysql
    ports:
      - port: 3306
        protocol: tcp

  - type: web
    name: ecommerce-backend
    env: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    autoDeploy: true
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://mysql:3306/ecommerce_db
      - key: SPRING_DATASOURCE_USERNAME
        value: root
      - key: SPRING_DATASOURCE_PASSWORD
        value: gowda
      - key: SPRING_DATASOURCE_DRIVER_CLASS_NAME
        value: com.mysql.cj.jdbc.Driver
