services:
  - type: web
    name: ecommerce-backend
    env: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./
    autoDeploy: true
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://mysql-19ceb2c-karunaducollections.h.aivencloud.com:19804/defaultdb?ssl-mode=REQUIRED
      - key: SPRING_DATASOURCE_USERNAME
        value: avnadmin
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: SPRING_DATASOURCE_DRIVER_CLASS_NAME
        value: com.mysql.cj.jdbc.Driver
      - key: SPRING_JPA_DATABASE_PLATFORM
        value: org.hibernate.dialect.MySQL8Dialect
      - key: SPRING_FLYWAY_BASELINE_ON_MIGRATE
        value: "true"
      - key: SPRING_FLYWAY_BASELINE_VERSION
        value: "0"

