



# Database (PostgreSQL on Render)
server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://dpg-d8lvkr6gvqtc73cg8i5g-a.oregon-postgres.render.com:5432/karunada_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:karunada_db_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:CBBcbjJopg5dgYZPAU59vxEzbPRjHXdt}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT Configurations
jwt.secret=${JWT_SECRET:karunada-ecommerce-secret-key-2026-secure-jwt-token-signing-key-minimum-512-bits}
jwt.expiration=${JWT_EXPIRATION:86400000}



# Email
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Razorpay
razorpay.key.id=${RAZORPAY_KEY_ID:}
razorpay.key.secret=${RAZORPAY_KEY_SECRET:}

# Logging
logging.level.org.springframework=INFO
logging.level.com.urbanman=DEBUG
