// Shared product catalogue — single source of truth
const products = [
  {
    id: 1,
    name: "Classic Shirt",
    price: 999,
    size: "M",
    color: "Blue",
    category: "Shirts",
    brand: "Urban Man",
    stock: 50,
    description: "Premium cotton shirt for formal wear.",
    image: "images/shirt.jpg",
    isNew: false,
    discount: 0
  },
  {
    id: 2,
    name: "Casual T-Shirt",
    price: 499,
    originalPrice: 699,
    size: "L",
    color: "Black",
    category: "T-Shirts",
    brand: "Urban Man",
    stock: 75,
    description: "Comfortable everyday casual t-shirt.",
    image: "images/tshirt.jpg",
    isNew: false,
    discount: 29
  },
  {
    id: 3,
    name: "Premium Linen Shirt",
    price: 1299,
    size: "M",
    color: "White",
    category: "New Collection",
    brand: "Urban Man",
    stock: 30,
    description: "Luxury breathable linen shirt.",
    image: "images/linen.jpg",
    isNew: true,
    discount: 0
  },
  {
    id: 4,
    name: "Slim Fit Jeans",
    price: 1499,
    originalPrice: 1999,
    size: "L",
    color: "Blue",
    category: "Jeans",
    brand: "Urban Man",
    stock: 60,
    description: "Modern slim-fit denim jeans.",
    image: "images/jeans.jpg",
    isNew: false,
    discount: 25
  },
  {
    id: 5,
    name: "Oversized Hoodie",
    price: 899,
    size: "XL",
    color: "Black",
    category: "New Collection",
    brand: "Urban Man",
    stock: 40,
    description: "Trendy oversized hoodie for casual days.",
    image: "images/hoodie.jpg",
    isNew: true,
    discount: 0
  },
  {
    id: 6,
    name: "Formal Blazer",
    price: 2499,
    originalPrice: 3499,
    size: "M",
    color: "Black",
    category: "Formal Wear",
    brand: "Urban Man",
    stock: 20,
    description: "Sharp formal blazer for office and events.",
    image: "images/blazer.jpg",
    isNew: true,
    discount: 29
  }
];
